// Run with: node wordpress/wp-content/plugins/bactive-cashier/tests/frontend.test.cjs
// Minimal DOM regression harness: exercises the shipped script without browser dependencies.
const fs=require('fs'),vm=require('vm'),assert=require('assert/strict'),path=require('path');
class E { constructor(tag){this.tag=tag;this.children=[];this.listeners={};this.className='';this.textContent='';this.attributes={};this.disabled=false;} append(...c){this.children.push(...c)} replaceChildren(...c){this.children=c} setAttribute(k,v){this.attributes[k]=v} addEventListener(k,v){this.listeners[k]=v} querySelector(s){return all(this).find(e=>s.startsWith('.')?e.className.split(' ').includes(s.slice(1)):e.tag===s)||null} reportValidity(){return true;} }
function all(e){return e.children.flatMap(c=>[c,...all(c)])} function text(e){return e.textContent+' '+e.children.map(text).join(' ')}
const code=fs.readFileSync(path.join(__dirname,'../assets/cashier.js'),'utf8');const key='11111111-1111-4111-8111-111111111111';
async function setup(sale,enabled=true,failCreate=false){const root=new E('div'),calls=[],storage=new Map();const config={api:'/api/',nonce:'nonce',staff:{id:1,name:'Associate'},training:true,enabled,activeKey:sale?key:'',logoutUrl:'http://localhost/logout'};const context={window:{BActiveCashier:config,addEventListener(){},confirm:()=>true},document:{getElementById:()=>root,createElement:t=>new E(t)},Intl,Map,URL,location:{href:'http://localhost/',origin:'http://localhost'},crypto:{randomUUID:()=>key},localStorage:{getItem:k=>storage.get(k),setItem:(k,v)=>storage.set(k,v),removeItem:k=>storage.delete(k)},setTimeout:()=>1,clearTimeout(){},fetch:async(url,o)=>{calls.push({url,...o});if(url.includes('products'))return{ok:true,json:async()=>({products:[{id:1,name:'<img onerror=bad>',attributes:'Size M, Green',price:'100.00',stock:2,image:''}],has_more:false})};if(o.method==='POST'&&failCreate)throw Error('Connection lost');return{ok:true,json:async()=>sale};}};vm.runInNewContext(code,context);await new Promise(setImmediate);return{root,calls,storage,context};}
function btn(root,label){return all(root).find(e=>e.tag==='button'&&e.textContent===label)}
(async()=>{
 const base={key,number:42,items:[{name:'Sample',quantity:1,total:'100.00'}],total:'100.00',method:'bactive_paymongo',invoice:'',email:'',can_cancel:false,payment_url:null};
 const pending=await setup({...base,status:'pending'});assert(!btn(pending.root,'Confirm cash received'));assert(!btn(pending.root,'Confirm invoice & hand over goods'));assert(text(pending.root).includes('Keep the goods with you'));
 const logout=all(pending.root).find(e=>e.tag==='a'&&e.textContent==='Sign out');assert(logout);pending.context.window.confirm=()=>false;let prevented=false;logout.listeners.click({preventDefault(){prevented=true;}});assert(prevented);
 const paid=await setup({...base,status:'paid'});assert(btn(paid.root,'Confirm invoice & hand over goods').disabled);const invoice=all(paid.root).find(e=>e.tag==='input'&&e.attributes.maxlength==='64');invoice.value='INV-1';invoice.listeners.input();assert(!btn(paid.root,'Confirm invoice & hand over goods').disabled);
 const stopped=await setup(null,false);assert(btn(stopped.root,'Add item').disabled);assert.equal(all(stopped.root).filter(e=>e.tag==='img').length,0,'Empty product image must not resolve to the cashier page');assert.equal(all(stopped.root).filter(e=>e.tag==='a'&&e.textContent==='Open secure payment page').length,0);
 const retry=await setup(null,true,true);btn(retry.root,'Add item').listeners.click();btn(retry.root,'Review sale & payment').listeners.click();await new Promise(setImmediate);assert(btn(retry.root,'Retry this same sale'));btn(retry.root,'Retry this same sale').listeners.click();await new Promise(setImmediate);const posts=retry.calls.filter(c=>c.method==='POST');assert.equal(posts.length,2);assert.equal(posts[0].body,posts[1].body);assert.equal(JSON.parse(posts[0].body).key,key);assert([...retry.storage.values()].every(v=>v===key));
 console.log('PASS: pending blocks cash/handover, invoice required, paused sales disabled, retry preserves exact payload/UUID, storage contains UUID only, active-sale logout warns, empty image omitted.');
})().catch(e=>{console.error(e);process.exitCode=1});
